# Generated by Django 5.0.2 on 2024-03-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentcourseenrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='enrolled_timestamp',
            new_name='enrolled_time',
        ),
    ]
