# Generated by Django 5.0.2 on 2024-03-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_profile_image_alter_courserating_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_image',
            new_name='profile_img',
        ),
    ]
