# Generated by Django 5.0.2 on 2024-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_student_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_text', models.TextField()),
                ('notif_for', models.CharField(max_length=500)),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notif_read_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '10. Notifications',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
