# Generated by Django 5.0.2 on 2024-03-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quiz_coursequiz_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
