# Generated by Django 5.0.2 on 2024-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_quizquestions_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='correct_ans',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
