# Generated by Django 5.0.2 on 2024-03-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_attemptquiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
    ]
