# Generated by Django 5.0.2 on 2024-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_faqs_alter_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Q. Contact Us',
            },
        ),
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': 'N. Attempted Questions/quiz'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': 'E. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'C. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'B. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': 'M. Course Quiz'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': 'G. Course Ratings and Reviews'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'P.  FAQs'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'J. Notifications'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'K. Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'verbose_name_plural': 'L. Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'D. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name_plural': 'I. Student Assignment'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': 'F. Enrolled Courses'},
        ),
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'verbose_name_plural': 'H. Student Favorite Courses'},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'verbose_name_plural': 'O. Course Study Materials'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'A. Teachers'},
        ),
    ]
