# Generated by Django 5.0.2 on 2024-03-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_contactus_alter_attemptquiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': '95. Attempted Questions/quiz'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '5. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': '98. Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '94. Course Quiz'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Ratings and Reviews'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': '97.  FAQs'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '91. Notifications'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': '92. Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'verbose_name_plural': '93. Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name_plural': '9. Student Assignment'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '6. Enrolled Courses'},
        ),
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'verbose_name_plural': '8. Student Favorite Courses'},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'verbose_name_plural': '96. Course Study Materials'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1. Teachers'},
        ),
    ]
